[package]
name = "qpprint"
version = "0.1.0"
authors = ["Jan Danielsson <jan.danielsson@qrnch.com>"]
edition = "2018"
license = "0BSD"
keywords = [ "cli", "console", "terminal", "format", "print" ]
repository = "https://github.com/openqrnch/qpprint"

[dependencies]
terminal_size = "0.1.12"

